### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by Nghia323223** [goodtube4u/goodtube#18]
When the script is used, it still show up normal downloading process, but after a while it just fails with an expired condition, expected the video to be saved.![image](https://github.com/goodtube4u/goodtube/assets/103433076/8ed63d3d-3570-41f2-9851-fc6b6f934d9f)

**Comment by goodtube4u** [comment]
That's odd, I actually updated the downloading servers to be more reliable today.

Can you link me to the video you were trying to download so I can test?

**Comment by Nghia323223** [comment]
https://m.youtube.com/watch?v=sFJ4sMJLBS8&pp=ygUPYW5oIHRyYWkgc2F5IGhp .

**Comment by goodtube4u** [comment]
Hmmm, have you refreshed youtube and pressed update on the popup that appears?

That will open a new tab, press update there as well, then refresh youtube.

I just tried downloading that video and worked no issues on my end?

**Comment by Nghia323223** [comment]
Okay, let me try.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: goodtube4u ***@***.***>
Đã gửi: Friday, July 5, 2024 5:26:37 PM
Đến: goodtube4u/goodtube ***@***.***>
Cc: Nghia323223 ***@***.***>; Author ***@***.***>
Chủ đề: Re: [goodtube4u/goodtube] Download failed (Issue #18)


Hmmm, have you refreshed youtube and pressed update on the popup that appears?

That will open a new tab, press update there as well, then refresh youtube.

I just tried downloading that video and worked no issues on my end?

**Comment by Nghia323223** [comment]
I done that more than once, but it stayed the same. Currently using firefox android.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Nguyen Nghĩa ***@***.***>
Đã gửi: Friday, July 5, 2024 5:27:30 PM
Đến: goodtube4u/goodtube ***@***.***>; goodtube4u/goodtube ***@***.***>
Cc: Author ***@***.***>
Chủ đề: Re: [goodtube4u/goodtube] Download failed (Issue #18)

Okay, let me try.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: goodtube4u ***@***.***>
Đã gửi: Friday, July 5, 2024 5:26:37 PM
Đến: goodtube4u/goodtube ***@***.***>
Cc: Nghia323223 ***@***.***>; Author ***@***.***>
Chủ đề: Re: [goodtube4u/goodtube] Download failed (Issue #18)


Hmmm, have you refreshed youtube and pressed update on the popup that appears?

That will open a new tab, press update there as well, then refresh youtube.

I just tried downloading that video and worked no issues on my end?

**Comment by Nghia323223** [comment]
Just tried this one, haven’t tried the others yet on the same device.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: goodtube4u ***@***.***>
Đã gửi: Friday, July 5, 2024 5:32:20 PM
Đến: goodtube4u/goodtube ***@***.***>
Cc: Nghia323223 ***@***.***>; Author ***@***.***>
Chủ đề: Re: [goodtube4u/goodtube] Download failed (Issue #18)


Hmm, that's hard for me to fix as I can't make it happen on my end. Are all videos failing to download or just that one?

**Comment by Nghia323223** [comment]
It succeeded on another video which was 360p. It might be because that yt blocked 720p+ streams, because the video that failed was 1080p.

**Comment by goodtube4u** [comment]
Nah downloads aren't related to video quality or any changes Youtube have made recently. If it works for one video, then it should work for both. No idea why only one would be failing? Can you test a few of them?

**Comment by Nghia323223** [comment]
Only a few suffered infinite buffering, most were okay.

**Comment by goodtube4u** [comment]
Hey man, I've just made an update to how downloads work. Can you update GoodTube and test on your end?

Should be fixed now :)

**Comment by Nghia323223** [comment]
It worked well, some still fails but they are not so much of a problem.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: goodtube4u ***@***.***>
Đã gửi: Saturday, July 6, 2024 6:38:44 AM
Đến: goodtube4u/goodtube ***@***.***>
Cc: Nghia323223 ***@***.***>; Author ***@***.***>
Chủ đề: Re: [goodtube4u/goodtube] Download failed (Issue #18)


Hey man, I've just made an update to how downloads work. Can you update GoodTube and test on your end?

Should be fixed now :)

**Comment by Nghia323223** [comment]
And also, on iphone orion, downloading and saving the video is not even an option, even with the download button. Only safari is possible.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Nguyen Nghĩa ***@***.***>
Đã gửi: Saturday, July 6, 2024 8:04:35 AM
Đến: goodtube4u/goodtube ***@***.***>; goodtube4u/goodtube ***@***.***>
Cc: Author ***@***.***>
Chủ đề: Re: [goodtube4u/goodtube] Download failed (Issue #18)

It worked well, some still fails but they are not so much of a problem.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: goodtube4u ***@***.***>
Đã gửi: Saturday, July 6, 2024 6:38:44 AM
Đến: goodtube4u/goodtube ***@***.***>
Cc: Nghia323223 ***@***.***>; Author ***@***.***>
Chủ đề: Re: [goodtube4u/goodtube] Download failed (Issue #18)


Hey man, I've just made an update to how downloads work. Can you update GoodTube and test on your end?

Should be fixed now :)

**Comment by goodtube4u** [comment]
Not an option? As in the button does not appear?

**Comment by Nghia323223** [comment]
The button does appear, but the video is not saved.

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: goodtube4u ***@***.***>
Đã gửi: Saturday, July 6, 2024 10:31:01 AM
Đến: goodtube4u/goodtube ***@***.***>
Cc: Nghia323223 ***@***.***>; Author ***@***.***>
Chủ đề: Re: [goodtube4u/goodtube] Download failed (Issue #18)


Not an option? As in the button does not appear?

**Comment by goodtube4u** [comment]
There have been further updates in the last 10 mins or so, can you update and try again?

**Comment by goodtube4u** [comment]
I've just had a good look at this. Unfortunately downloads are not possible on iOS.

These have now been disabled. If you really want to download stuff, you can do it on a desktop computer or Android phone.
